version: "2"

run:
  timeout: 1m

formatters:
  enable:
    - gci
    - gofmt
    - goimports

linters:
  default: all

  disable:
    - depguard            # We don't have any packages we need to block
    - paralleltest        # Tests are fast already and paralellizing them adds complexity
    - wsl                 # We use wsl_v5 instead
    - wrapcheck           # Adds too much bloat, many of the errors are contextual enough and don't need wrapping

  exclusions:
    rules:
      - path: _test.go
        linters:
          - dupl # We don't mind duplicated code in tests. It helps with clarity

