version: "2"

run:
  timeout: 1m

formatters:
  enable:
    - gci
    - gofmt
    - goimports

linters:
  default: all

  exclusions:
    rules:
      - path: _test.go
        linters:
          - dupl # We don't mind duplicated code in tests. It helps with clarity

