version: 2

before:
  hooks:
    - go mod download

builds:
  - id: git-get
    main: ./cmd/
    binary: git-get
    ldflags:
      - -s -w 
      - -X git-get/pkg/cfg.version={{.Version}} 
      - -X git-get/pkg/cfg.commit={{.Commit}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
  - id: git-get-macos
    main: ./cmd/
    binary: git-get
    ldflags:
      - -s -w 
      - -X git-get/pkg/cfg.version={{.Version}} 
      - -X git-get/pkg/cfg.commit={{.Commit}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    ids:
      - git-get
    name_template: "git-get_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}{{- if .Amd64 }}v{{ .Amd64 }}{{ end }}"
    formats:
      - tar.gz
      - zip
    format_overrides:
      - goos: windows
        formats: [zip]
    # Don't include any additional files into the archives (such as README, CHANGELOG etc). 
    files:
      - none*
  - id: macos-archive
    ids:
      - git-get-macos
    name_template: "git-get_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}{{- if .Amd64 }}v{{ .Amd64 }}{{ end }}"
    formats:
      - tar.gz
    files:
      - none* 

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
      - typo

release:
  github:
    owner: grdl
    name: git-get

brews:
  - name: git-get
    ids:
      - macos-archive
    repository:
      owner: grdl
      name: homebrew-tap
      branch: master
    directory: Formula
    commit_author:
      name: Grzegorz Dlugoszewski
      email: git-get@grdl.dev
    homepage: https://github.com/grdl/git-get/
    description: Better way to clone, organize and manage multiple git repositories
    license: MIT
    install: |
      bin.install "git-get"
      bin.install_symlink "git-get" => "git-list"
    test: |
      system "#{bin}/git-get", "--version"
      system "#{bin}/git-list", "--version"

nfpms:
  - id: packages
    package_name: git-get
    license: MIT
    maintainer: Grzegorz Dlugoszewski <git-get@grdl.dev>
    homepage: https://github.com/grdl/git-get
    bindir: /usr/local/bin
    dependencies:
      - git
    description: Better way to clone, organize and manage multiple git repositories
    formats:
      - deb
      - rpm
    contents:
      - src: /usr/local/bin/git-get
        dst: /usr/local/bin/git-list
        type: "symlink"

scoops:
  - name: git-get
    repository:
      owner: grdl
      name: homebrew-tap
      branch: master
    directory: Scoop
    url_template: "https://github.com/grdl/git-get/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Grzegorz Dlugoszewski
      email: git-get@grdl.dev
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/grdl/git-get"
    description: "Better way to clone, organize and manage multiple git repositories"
    license: MIT
    post_install: [
      "New-Item -ItemType HardLink -Path \"$dir\\git-list.exe\" -Target \"$dir\\git-get.exe\" -Force | Out-Null",
      "scoop shim add git-list \"$dir\\git-list.exe\""
    ],
    post_uninstall: [
      "scoop shim rm git-list"
    ]
