before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/git-get/main.go
    binary: "git-get"
    goos:
      - linux
      - darwin
      - windows

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
