name: build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Set up Git
        run: git config --global user.email "grdl@example.com" && git config --global user.name "grdl"
      - name: Run go test
        run: CGO_ENABLED=0 GOOS=linux go test ./... -v
